### ISSUE TITLE
source tree lacks code formatting style file

### ISSUE THREAD

**Issue by berndpfrommer** [dawonn/vectornav#89]
Could one of the maintainers please post a formatting style file? I believe this is the standard ROS one:

```
---
Language: Cpp
BasedOnStyle: Google

AccessModifierOffset: -2
AlignAfterOpenBracket: AlwaysBreak
BraceWrapping:
  AfterClass: true
  AfterFunction: true
  AfterNamespace: true
  AfterStruct: true
BreakBeforeBraces: Custom
ColumnLimit: 100
ConstructorInitializerIndentWidth: 0
ContinuationIndentWidth: 2
DerivePointerAlignment: false
PointerAlignment: Middle
ReflowComments: false
...


```
